import type { Config } from "@netlify/functions";
import { db } from "../../db/index.js";
import { works, siteConfig, scheduleEvents } from "../../db/schema.js";

const SEED_WORKS = [
  {
    title: "三景之章",
    year: 2024,
    category: "Classic",
    medium: "Piano Solo",
    description: "The suite is titled Three Scenes, and as the name suggests, it depicts three different scenes drawn from everyday life. The work as a whole adopts a relatively modern compositional language and sonic expression, drawing inspiration from the abstract descriptive style of Impressionist composers. At the same time, it incorporates a number of extended instrumental techniques, giving the music a fresh and intriguing character.\n\nPebbles employs an artificially constructed pitch series. Through various permutations of a seven-note row, the work seeks to evoke the swaying and frictional sensation of pebbles being washed by flowing water. Particular emphasis is placed on the minor-second intervals within the row, using this distinctive sonority to portray the smoothness and delicacy of the pebbles. The movement is vivid, lively, and highly characteristic in style.\n\nTidal Flat adopts developmental techniques associated with minimalism. Its extremely concise texture creates a striking sense of alternation between the left and right hands. The sonic design is carefully crafted, with changing horizontal intervals and contrapuntal relationships unfolding in a way that simultaneously sustains continuity and generates progression, resulting in an organic musical flow. The piece aims to depict the swaying of waves along the tidal flats and the ebb and flow of the tides — advancing and retreating, sometimes calm and gradual, sometimes urgent and intense. Through the cyclical motion of the sea, the tidal flat reveals its unique atmosphere and leaves a profound impression on the listener.\n\nWillow pioneers the use of extended performance techniques. While maintaining consistency in its melodic and harmonic framework, the work continuously stretches and restructures musical figures, creating connections that seem delicate yet inseparable. As expressed in the ancient poetic image, \u201cThousands of willow branches brush the face like silken threads; green mist ...",
    programNote: "",
    premiereInfo: "",
    festivalSelections: "",
    youtubeUrl: "",
    soundcloudUrl: "",
    audioUrl: "",
    scorePdfUrl: "",
    coverImage: "",
    tags: "[]",
    featured: false,
    sortOrder: 0,
  },
  {
    title: "A Voice Intolerable to Heaven and Earth",
    year: 2025,
    category: "Electronics",
    medium: "Fixed Media",
    description: "This electroacoustic music work explores the imbalance and reconstruction of order. Emerging within time and space, it drifts between reality and illusion, where sounds continually expand through cycles of creation and collapse. Through the reassembly of old structures and the emergence of new textures, resonance unfolds across time, becoming an echo that trembles throughout the cosmos.\n\nStructured in four sections, the piece employs the Kyma system for sound synthesis and reconfiguration, alongside additional processing techniques to create distinctive sonic transformations. The work seeks to express the idea that all things are neither bound by fixed forms nor confined by rigid rules, but may ultimately return to the currents of time and space \u2014 probing origins while opening new possibilities.\n\nWithin this convergence, sound flows through spacetime as something both primordial and eternal, embodying a presence that is raw, boundless, and enduring.",
    programNote: "",
    premiereInfo: "USA Premiere",
    festivalSelections: "ICMC, Seamus, CCMC, Somi China",
    youtubeUrl: "https://youtu.be/ebndJDO4EEU?si=VufM_RQoImmsi5ZQ",
    soundcloudUrl: "",
    audioUrl: "",
    scorePdfUrl: "",
    coverImage: "",
    tags: "[]",
    featured: false,
    sortOrder: 0,
  },
  {
    title: "\u8774\u8776 \u914d\u4e50",
    year: 2024,
    category: "Film Scoring",
    medium: "",
    description: "",
    programNote: "",
    premiereInfo: "",
    festivalSelections: "",
    youtubeUrl: "",
    soundcloudUrl: "",
    audioUrl: "",
    scorePdfUrl: "",
    coverImage: "",
    tags: "[]",
    featured: false,
    sortOrder: 0,
  },
  {
    title: "\u4e09\u5929\u7684\u8def\u7a0b\u4e24\u5929\u5230",
    year: 2024,
    category: "Vocal ",
    medium: "For Chinese Opera Vocal and Piano",
    description: "Arrange For Chinese folk song \"San Tian Lu Cheng Liang Tian Zou\"",
    programNote: "",
    premiereInfo: "",
    festivalSelections: "",
    youtubeUrl: "https://youtu.be/feRFZ7-K8tM",
    soundcloudUrl: "",
    audioUrl: "",
    scorePdfUrl: "",
    coverImage: "",
    tags: "[]",
    featured: false,
    sortOrder: 0,
  },
  {
    title: "1/2",
    year: 2025,
    category: "Interactive Music",
    medium: "For Mediapipe and Max/MSP",
    description: "1/2 is an interactive music work exploring a liminal state between physical presence and digital mediation. Built with MediaPipe-based visual sensing and Max/MSP, the piece transforms bodily movement into unstable and continuously evolving sound behavior. Rather than functioning as direct control, gestures are fragmented, delayed, and reinterpreted, allowing the body to drift between representation and abstraction.\n\nThe work focuses on the relationship between performer and system, where both exist within a shared feedback loop. Whispers, growls, and deconstructed piano timbres are processed in real time, creating a sonic environment that moves between intimacy and distortion, control and unpredictability.\n\nRemaining intentionally incomplete, 1/2 reflects on contemporary experiences of partial presence in digitally mediated spaces. The piece invites listeners into a shifting environment where perception, agency, and identity are continuously negotiated rather than fixed.",
    programNote: "",
    premiereInfo: "",
    festivalSelections: "",
    youtubeUrl: "",
    soundcloudUrl: "",
    audioUrl: "",
    scorePdfUrl: "",
    coverImage: "",
    tags: "[]",
    featured: false,
    sortOrder: 0,
  },
  {
    title: "Linger Silence",
    year: 2023,
    category: "Vocal ",
    medium: "For Piano and Pop Soprano Vocal",
    description: "Long Silence is a work for piano and voice. Through restrained piano textures and drifting vocal lines, the piece creates a quiet emotional space shaped by stillness, distance, and gradual tension. Focusing on the expressive power of silence, the work unfolds between sound and pause, allowing emotion to emerge slowly and subtly.",
    programNote: "",
    premiereInfo: "",
    festivalSelections: "",
    youtubeUrl: "",
    soundcloudUrl: "",
    audioUrl: "",
    scorePdfUrl: "",
    coverImage: "",
    tags: "[]",
    featured: false,
    sortOrder: 0,
  },
  {
    title: "\u5c71\u6c34\u56ed\u6797\uff08feat.\u4ee3\u8f69\u8bda\uff09",
    year: 2026,
    category: "Electronics",
    medium: "For 4 Virtual Shaped Guitars and Electronics",
    description: "",
    programNote: "",
    premiereInfo: "",
    festivalSelections: "",
    youtubeUrl: "",
    soundcloudUrl: "",
    audioUrl: "",
    scorePdfUrl: "",
    coverImage: "",
    tags: "[]",
    featured: false,
    sortOrder: 0,
  },
  {
    title: "\u65f6\u4ee3\u8deb\u97ff Echoes of the Era",
    year: 2024,
    category: "Electronics",
    medium: "FIxed Media",
    description: "Echoes of the Era is a fixed media electroacoustic work inspired by a TikTok video in which a creator described the unstable signal of wireless English listening-test earphones used in CET examinations. The interruptions, glitches, and sudden distortions transformed what was originally a functional communication device into an accidental sonic landscape charged with tension and uncertainty.\n\nUsing fragmented speech, signal noise, electronic interference, and unstable frequency textures as primary materials, the work explores the fragile relationship between human perception and digital media systems. Sounds continuously disconnect, repeat, and re-emerge, blurring the boundary between communication failure and musical expression.\n\nRather than documenting a specific event, Echoes of the Era reflects on the instability, anxiety, and fragmentation embedded within contemporary technological life. Through broken transmissions and distorted voices, the piece attempts to capture the subtle \u201cfootsteps\u201d of an era moving forward beneath layers of noise and information.",
    programNote: "",
    premiereInfo: "",
    festivalSelections: "",
    youtubeUrl: "",
    soundcloudUrl: "",
    audioUrl: "",
    scorePdfUrl: "",
    coverImage: "",
    tags: "[]",
    featured: false,
    sortOrder: 0,
  },
  {
    title: "Sensitive Bounce",
    year: 2025,
    category: "Multi-media",
    medium: "For Contemporary Dance Video and Electronics",
    description: "Sensitive Bounce is a fixed media electroacoustic work inspired by the concept of electrostatics in ancient Chinese physics and natural philosophy. The piece aims to reinterpret and communicate traditional Chinese understandings of invisible forces and material interactions through contemporary electronic sound.\n\nDrawing from the phenomena of attraction, repulsion, accumulation, and discharge, the work transforms microscopic physical movement into dynamic sonic structures. Fragmented pulses, unstable resonances, frictional textures, and rapidly shifting spatial gestures form a constantly changing sound environment that reflects both scientific curiosity and philosophical imagination.",
    programNote: "",
    premiereInfo: "",
    festivalSelections: "",
    youtubeUrl: "",
    soundcloudUrl: "",
    audioUrl: "",
    scorePdfUrl: "",
    coverImage: "",
    tags: "[]",
    featured: false,
    sortOrder: 0,
  },
  {
    title: "I Am Becoming Death",
    year: 2024,
    category: "Multi-media",
    medium: "For Short Video and Electronics",
    description: "",
    programNote: "",
    premiereInfo: "",
    festivalSelections: "",
    youtubeUrl: "",
    soundcloudUrl: "",
    audioUrl: "",
    scorePdfUrl: "",
    coverImage: "",
    tags: "[]",
    featured: false,
    sortOrder: 0,
  },
  {
    title: "\u5b88\u62a4\u8005\u7684\u8a93\u8a00\uff08feat. Zhang Wen)",
    year: 2024,
    category: "Vocal ",
    medium: "For BIg Band and 2 Vocals",
    description: "",
    programNote: "",
    premiereInfo: "",
    festivalSelections: "",
    youtubeUrl: "",
    soundcloudUrl: "",
    audioUrl: "",
    scorePdfUrl: "",
    coverImage: "",
    tags: "[]",
    featured: false,
    sortOrder: 0,
  },
  {
    title: "\u68b5\u97f3\u56de\u5eca",
    year: 2024,
    category: "Vocal ",
    medium: "For AI Vocal and Synth",
    description: "This work explores the emotional and spiritual space between contemporary urban life and traditional Chinese musical culture. Through the integration of Chinese traditional and Buddhist musical elements, the piece seeks to offer listeners a moment of stillness within the fast-paced rhythm of modern cities \u2014 a temporary sanctuary where one may slow down, reflect, and reconnect with inner calm.\n\nThe work also emphasizes the psychological and therapeutic qualities of Buddhist music. Its distinctive tonal language, instrumental colors, and meditative atmosphere possess the ability to soothe emotions, reduce anxiety, and deepen states of contemplation. By combining traditional sonic aesthetics with contemporary expression, the piece attempts to reveal how ancient musical culture may continue to serve as a meaningful tool for emotional healing and mental balance in modern society.",
    programNote: "Intro:\n\uff08\u82f1\u6587\u94ed\u5531\uff09\nVerse 1:\n\u5728\u672a\u6765\u7684\u57ce\u5e02\u4e2d\uff0c\n\u79d1\u6280\u7e41\u534e\u5374\u8ff7\u832b\uff0c\n\u5fc3\u4e2d\u5b64\u72ec\u96be\u8a00\u8bf4\uff0c\n\u5bfb\u627e\u5185\u5fc3\u7684\u65b9\u5411\u3002\nChorus:\n\u672a\u6765\u7684\u5149\uff0c\u7167\u4eae\u5fc3\u623f\uff0c\n\u53e4\u8001\u7684\u7ecf\u6587\uff0c\u8bc9\u8bf4\u5e0c\u671b\uff0c\n\u7a7f\u8d8a\u65f6\u7a7a\uff0c\u627e\u5230\u5b81\u9759\uff0c\n\u672a\u6765\u7684\u8def\uff0c\u7531\u6211\u4eec\u5f00\u521b\u3002\n(Hook\uff09\nChorus:\n\u672a\u6765\u7684\u5149\uff0c\u7167\u4eae\u5fc3\u623f\uff0c\n\u53e4\u8001\u7684\u7ecf\u6587\uff0c\u8bc9\u8bf4\u5e0c\u671b\uff0c\n\u7a7f\u8d8a\u65f6\u7a7a\uff0c\u627e\u5230\u5b81\u9759\uff0c\n\u672a\u6765\u7684\u8def\uff0c\u7531\u6211\u4eec\u5f00\u521b\u3002\nChorus:\n\u672a\u6765\u7684\u5149\uff0c\u7167\u4eae\u5fc3\u623f\uff0c\n\u53e4\u8001\u7684\u7ecf\u6587\uff0c\u8bc9\u8bf4\u5e0c\u671b\uff0c\n\u7a7f\u8d8a\u65f6\u7a7a\uff0c\u627e\u5230\u5b81\u9759\uff0c\n\u672a\u6765\u7684\u8def\uff0c\u7531\u6211\u4eec\u5f00\u521b\u3002\nChorus:\n\u672a\u6765\u7684\u5149\uff0c\u7167\u4eae\u5fc3\u623f\uff0c\n\u53e4\u8001\u7684\u7ecf\u6587\uff0c\u8bc9\u8bf4\u5e0c\u671b\uff0c\n\u7a7f\u8d8a\u65f6\u7a7a\uff0c\u627e\u5230\u5b81\u9759\uff0c\n\u672a\u6765\u7684\u8def\uff0c\u7531\u6211\u4eec\u5f00\u521b\u3002\nChorus:\n\u672a\u6765\u7684\u5149\uff0c\u7167\u4eae\u5fc3\u623f\uff0c\n\u53e4\u8001\u7684\u7ecf\u6587\uff0c\u8bc9\u8bf4\u5e0c\u671b\uff0c\n\u7a7f\u8d8a\u65f6\u7a7a\uff0c\u627e\u5230\u5b81\u9759\uff0c\n\u672a\u6765\u7684\u8def\uff0c\u7531\u6211\u4eec\u5f00\u521b\u3002\n(Hook)\nChorus:\n\u672a\u6765\u7684\u5149\uff0c\u7167\u4eae\u5fc3\u623f\uff0c\n\u53e4\u8001\u7684\u7ecf\u6587\uff0c\u8bc9\u8bf4\u5e0c\u671b\uff0c\n\u7a7f\u8d8a\u65f6\u7a7a\uff0c\u627e\u5230\u5b81\u9759\uff0c\n\u672a\u6765\u7684\u8def\uff0c\u7531\u6211\u4eec\u5f00\u521b\u3002",
    premiereInfo: "",
    festivalSelections: "",
    youtubeUrl: "",
    soundcloudUrl: "",
    audioUrl: "",
    scorePdfUrl: "",
    coverImage: "",
    tags: "[]",
    featured: false,
    sortOrder: 0,
  },
  {
    title: "Normal Human Research",
    year: 2025,
    category: "Interactive Music",
    medium: "For Midi-controller and Max/MSP",
    description: "Normal Human Research is a work for MIDI controller and live electronics that explores identity and social expectations in contemporary society. In a fast-changing digital era, individuals are constantly shaped by technology, information, and collective norms.\n\nThrough fragmented voices, mechanical textures, and real-time controller performance, the piece creates an unstable sonic environment that reflects anxiety, adaptation, and the reconstruction of self-identity. The work questions what kind of people our era demands, while exploring the tension between individuality and social systems.",
    programNote: "",
    premiereInfo: "",
    festivalSelections: "",
    youtubeUrl: "",
    soundcloudUrl: "",
    audioUrl: "",
    scorePdfUrl: "",
    coverImage: "",
    tags: "[]",
    featured: false,
    sortOrder: 0,
  },
];

const SEED_SCHEDULE = [
  {
    eventDate: "2026-06-15",
    title: "NYCEMF 2026 \u2014 Electroacoustic Music Festival",
    venue: "New York City Electroacoustic Music Festival",
    cityCountry: "New York, USA",
    workPerformed: "A Voice Intolerable to Heaven and Earth",
    link: "",
  },
  {
    eventDate: "2026-07-22",
    title: "ICMC 2026 \u2014 International Computer Music Conference",
    venue: "Hamburg University of Music and Theatre",
    cityCountry: "Hamburg, Germany",
    workPerformed: "A Voice Intolerable to Heaven and Earth",
    link: "",
  },
  {
    eventDate: "2026-09-10",
    title: "SEAMUS 2026 National Conference",
    venue: "Virginia Tech",
    cityCountry: "Blacksburg, VA, USA",
    workPerformed: "1/2",
    link: "",
  },
  {
    eventDate: "2026-05-01",
    title: "CCMC Futura \u2014 Computer Music Conference",
    venue: "Kyoto University",
    cityCountry: "Kyoto, Japan",
    workPerformed: "A Voice Intolerable to Heaven and Earth",
    link: "",
  },
];

const SEED_SITE = {
  hero: {
    displayName: "Populian",
    alias: "Faming Qin \u79e6\u53d1\u9e23",
    subtitle: "Electroacoustic Composer \u00b7 Interactive Media Artist \u00b7 Music Technology Researcher",
    statement: "Faming Qin, also known as Populian, is an electroacoustic composer, interactive media artist, and music technology researcher based in Xi'an, China.",
    heroImage: "/uploads/1778921569007-758016751.png",
    portraitImage: "/uploads/1778921564791-332284195.jpeg",
    featuredWorkIds: [],
  },
  about: {
    biography: "Qin Faming (Populian) is a Chinese composer, sound artist, and multimedia creator currently studying Electronic Music Composition at Xi\u2019an Conservatory of Music. His work focuses on electroacoustic music, interactive performance systems, sound design, and cross-media composition, with a particular interest in the relationships between body, space, technology, and perception.\n\nHis artistic practice combines electronic sound, instrumental textures, spatial audio, and algorithmic interaction, exploring the fluid boundaries between reality and virtuality. Through fragmentation, looping, distortion, and reconstruction, he creates immersive sonic environments that emphasize psychological space and temporal transformation.\n\nAlongside composition, he actively explores emerging technologies in artistic creation, working with Max/MSP, Kyma, SuperCollider, Ableton Live, Python, and sensor-based systems for real-time interaction and sound research. Through his work, he seeks to develop a contemporary sonic language that balances technical experimentation with emotional and poetic depth.",
    education: [
      { institution: "Xi'an Conservatory of Music", degree: "Bachelor of Music in Electroacoustic Composition", years: "2023\u2013Present" },
      { institution: "University of Oregon \u2013 Future Music Oregon Summer Academy", degree: "Kyma System Coursework", years: "" },
    ],
    skills: ["Max/MSP", "Ableton Live", "Kyma", "Logic Pro", "Pro Tools", "VCV Rack", "Python", "Interactive Media", "AI + Music Systems", "Sound Design"],
    awards: ["ICMC 2026 Selection", "SEAMUS 2026 Selection", "CCMC Futura Award", "China Collegiate Computing Competition Third Prize"],
    researchInterests: [
      { title: "Electroacoustic Music Composition", explanation: "Electronics Sound Design and the construct of composition techniques." },
      { title: "Network Music Performance", explanation: "Real-time online performance and collaborative art." },
    ],
    artisticStatement: "My work often begins with an ambiguous sensory state \u2014 a feeling of space, memory, physical tension, or emotional residue that cannot be clearly described through conventional language. Rather than treating music as purely melodic or structural organization, I approach sound as a perceptual architecture: a medium capable of reshaping how we experience time, space, and presence.\n\nI am particularly interested in the unstable relationship between electronic sound and reality. Instead of linear narratives, I tend to explore interruption, fragmentation, distortion, and states that exist between the physical and the virtual. The materials in my works frequently emerge from subtle bodily gestures, environmental recordings, degraded instrumental textures, and reconstructed everyday sounds. Through looping, spatialization, delay, and real-time processing, these materials gradually detach from their original context and evolve into immersive sonic environments suspended between memory and illusion.\n\nIn interactive works, I focus on uncertainty within systems of control. I do not view technology as a perfectly obedient tool, but rather as an active participant capable of producing unpredictable behaviors alongside the performer. Delays, instability, sensor errors, and algorithmic deviations are not technical flaws to eliminate, but expressive elements embedded within the work itself. For me, technology becomes a way to reveal vulnerability, mediation, and the shifting boundaries between human intention and machine response.\n\nMy practice is influenced by electroacoustic music, cinema, installation art, and contemporary digital culture. I aim to create works that are both physically immersive and emotionally resonant \u2014 pieces that invite listeners into unstable spaces where sound functions simultaneously as memory, body, atmosphere, and transformation.",
    aliasExplanation: "",
  },
  contact: {
    email: "populianmusic@gmail.com",
    socialLinks: { instagram: "", soundcloud: "", youtube: "", github: "" },
    cvPdfUrl: "",
    shortBio: "",
    longBio: "",
    pressPhotoUrl: "",
    displayName: "Populian ",
    alias: "Faming Qin",
  },
};

export default async (req: Request) => {
  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  const existingWorks = await db.select().from(works);
  if (existingWorks.length > 0) {
    return Response.json({ message: "Data already exists. Use force=true to overwrite.", seeded: false });
  }

  // Seed all 13 works
  for (const w of SEED_WORKS) {
    await db.insert(works).values(w);
  }

  // Seed 4 schedule events
  for (const ev of SEED_SCHEDULE) {
    await db.insert(scheduleEvents).values(ev);
  }

  // Seed site config
  for (const [key, value] of Object.entries(SEED_SITE)) {
    await db.insert(siteConfig).values({
      configKey: key,
      configValue: JSON.stringify(value),
    });
  }

  return Response.json({
    success: true,
    seeded: true,
    works: SEED_WORKS.length,
    schedule: SEED_SCHEDULE.length,
    configs: Object.keys(SEED_SITE).length,
  });
};

export const config: Config = {
  path: "/api/seed",
};
